# -*- coding: utf-8 -*-
"""Copy of Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KjgNtLruELMjnPeMY5rtSC4LPtCDCiuZ

**WAP to read asembly level and their address and generate a  symbol table bold text**
"""

symbol_table = {}

n = int(input("Enter number of symbols: "))

for _ in range(n):
    label = input("Enter label: ")
    address = input("Enter address: ")
    symbol_table[label] = address

print("\n----- Symbol Table -----")
print("Label\tAddress")

for label, address in symbol_table.items():
    print(f"{label}\t{address}")

"""wap a python to simulate the location counter while processing assemble instruction

"""

start = int(input("Enter starting address: "))

n = int(input("Enter number of assembly instructions: "))

lc = start

print("\nLocation Counter")
print("----------------------------")

for i in range(n):
    instruction = input("Enter instruction: ")

    print(f"{lc}\t{instruction}")

    # Update Location Counter
    if instruction.startswith("WORD"):
        lc += 3
    elif instruction.startswith("RESW"):
        value = int(instruction.split()[1])
        lc += 3 * value
    elif instruction.startswith("RESB"):
        value = int(instruction.split()[1])
        lc += value
    elif instruction.startswith("BYTE"):
        operand = instruction.split()[1]
        if operand.startswith("C'"):
            lc += len(operand) - 3
        elif operand.startswith("X'"):
            lc += (len(operand) - 3) // 2
    else:
        # Default instruction size
        lc += 3

print("\nFinal Location Counter =", lc)